openapi: 3.0.1
info:
  title: project Recorder Module
  description: project Recorder showcasing operation around project Recorder.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Tenants module
  url: http://tenancy.docs.local
servers:
- url: 'http://localhost:8080'
tags:
- name: Section
  description: Everything about Section management
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /sections:
    get:
      tags:
      - Section
      summary: Get all section records
      operationId: getAllSections
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: './schemas/SectionResponse.yml#/SectionResponse/SectionList'
        500:
          description: Server Error
          content: {}
      security:
      - bearerAuth: []
components:
  headers:
    restartRowId:
      description: Restart row ID for pagination
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []